variables:
    SolutionBaseName: 'DFC.HtmlToDataTranslator'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.6.5
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

pr:
  - master
    
jobs:
- job: Build
  displayName: Build
  workspace:
    clean: all
  
  # Build Package + Unit Tests
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 3.1.101
      TestSuffix: UnitTests

  - task: PowerShell@2
    displayName: "Pack and version nuget file"
    inputs:      
      targetType: inline
      script: |
        dotnet pack $(SolutionBaseName)/$(SolutionBaseName).csproj --no-build -c Release -o $(build.artifactstagingdirectory)\\packages /p:Version=$(Build.BuildNumber)

  # And publish it so we can release it in a separate release definition
  - task: PublishBuildArtifacts@1
    displayName:  "Publish build artifacts"
    inputs:
      ArtifactName: "Packages"
      PathtoPublish: "$(build.artifactstagingdirectory)\\packages"