variables:
    SolutionBaseName: 'DFC.HtmlToDataTranslator'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.6.5
    endpoint: 'GitHub (ESFA)'

pr:
  - master
    
jobs:
- job: Build
  displayName: Build
  pool:
    name: NCS - CI and CD
    demands:
    - msbuild
    - visualstudio
  
  steps:
  # Copy app settings template file, otherwise the build will fail
  - task: PowerShell@2
    displayName: 'Rename app settings template'    
    inputs:
      targetType: inline
      script:
        Copy-Item -Path "$(System.DefaultWorkingDirectory)\$(SolutionBaseName).IntegrationTests\appsettings-template.json" -Destination "$(System.DefaultWorkingDirectory)\$(SolutionBaseName).IntegrationTests\appsettings.json"

  - task: DotNetCoreCLI@2  
    inputs:
      command: custom
      custom: clean

  # Build Package + Unit Tests
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      DotNetCoreVersion: 2.2.402
      TestSuffix: UnitTests

  - task: PowerShell@2
    displayName: "Pack and version nuget file"
    inputs:      
      targetType: inline
      script: |
        dotnet pack DFC.FindACourseClient/DFC.FindACourseClient.csproj --no-build -c Release -o $(build.artifactstagingdirectory)\\packages /p:Version=$(Build.BuildNumber)

  # And publish it so we can release it in a separate release definition
  - task: PublishBuildArtifacts@1
    displayName:  "Publish build artifacts"
    inputs:
      ArtifactName: "Packages"
      PathtoPublish: "$(build.artifactstagingdirectory)\\packages"